theme: minima
title: Prof. Thonimar V. Alencar
author: 
name: Thonimar V. Alencar
github_username:  thonimar
email: thonimar.souza@ufes.br
description: >- #
  Página do Prof. Thonimar V. Alencar.
baseurl: "/ufes" # This is important for the URL
url: "https://thonimar.github.io" # This is your GitHub Pages URL
plugins:
  - jekyll-seo-tag
minima:
  skin: classic
  social_links:
    - title: Meu repositório GitHub
      icon: github
      url: "https://github.com/thonimar/"
