theme: minima
title: Prof. Thonimar V. Alencar
author:
  name: Thonimar V. Alencar
github_username: thonimar
email: thonimar.souza@ufes.br
description: >-
  Universidade Federal do Espírito Santo (UFES), São Mateus.
baseurl: "/ufes"
url: "https://thonimar.github.io"
plugins:
  - jekyll-seo-tag
minima:
  skin: classic
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/thonimar/"
    - title: E-mail
      icon: email
      url: "mailto:thonimar.souza@ufes.br"
